<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'ParsedownExtra' => array($vendorDir . '/erusev/parsedown-extra'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
);
